# Generated by Django 4.0.3 on 2022-04-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boo', models.BooleanField()),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес для самовызова')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.IntegerField(verbose_name='Адрес')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('entrance', models.IntegerField(blank=True, null=True, verbose_name='Пподъезд')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон')),
                ('house', models.IntegerField(blank=True, null=True, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
