# Generated by Django 4.0.3 on 2022-04-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.CharField(max_length=30, verbose_name='Тип пиццы')),
            ],
        ),
        migrations.CreateModel(
            name='SizePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер пиццы')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.CharField(blank=True, max_length=16, null=True, verbose_name='')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка')),
                ('image', models.ImageField(upload_to=None, verbose_name='Фотография')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPizza.dough')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPizza.sizepizza')),
            ],
        ),
    ]
