# Generated by Django 4.0.3 on 2022-04-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='new',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='imange/food/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.discount'),
        ),
    ]
