# Generated by Django 4.0.3 on 2022-04-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0002_alter_drinks_image_alter_food_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, verbose_name='Цена')),
            ],
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AddField(
            model_name='order',
            name='ordermain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iPizza.ordermain', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
