# Generated by Django 4.0.3 on 2022-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0003_ordermain_alter_drinks_options_order_ordermain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drinks',
        ),
        migrations.AddField(
            model_name='order',
            name='drinks',
            field=models.ManyToManyField(blank=True, null=True, to='iPizza.drinks'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='iPizza.food'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, null=True, to='iPizza.pizza'),
        ),
    ]
