# Generated by Django 4.0.3 on 2022-04-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0005_remove_order_drinks_order_drinks_remove_order_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='combo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iPizza.combo', verbose_name='Комбо'),
            preserve_default=False,
        ),
    ]
