# Generated by Django 4.0.3 on 2022-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0007_category_categorysushi_food_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Цена'),
        ),
    ]
