# Generated by Django 4.0.3 on 2022-04-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0009_alter_ordermain_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.combo', verbose_name='Комбо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordermain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.ordermain', verbose_name='Заказ'),
        ),
    ]
