# Generated by Django 4.0.3 on 2022-04-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0010_alter_order_combo_alter_order_ordermain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.drinks')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.food')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iPizza.pizza')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPizza.stock')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
