# Generated by Django 4.0.3 on 2022-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0011_alter_stock_options_stock_name_stockmain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysushi',
            options={'verbose_name': 'Категория суши', 'verbose_name_plural': 'Категория суши'},
        ),
    ]
