# Generated by Django 4.0.3 on 2022-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPizza', '0012_alter_categorysushi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название акции'),
        ),
    ]
