# Generated by Django 4.0.3 on 2022-04-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.TextField(verbose_name='Описание')),
                ('img_1', models.ImageField(upload_to='imange/food', verbose_name='Картинка')),
                ('text_2', models.TextField(blank=True, verbose_name='Описание')),
                ('img_2', models.ImageField(blank=True, upload_to='imange/food', verbose_name='Картинка')),
                ('certificate', models.ImageField(upload_to='', verbose_name='сертификат')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(verbose_name='Номера телефонов')),
                ('text', models.TextField(verbose_name='Опишите суть вопроса, ситуацию')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.city', verbose_name='Выберите город')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
