# Generated by Django 4.0.3 on 2022-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img_1',
            field=models.ImageField(upload_to='image/food', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='image/food', verbose_name='Картинка'),
        ),
    ]
