# Generated by Django 4.0.3 on 2022-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_about_img_1_alter_about_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='image/document', verbose_name='сертификат'),
        ),
    ]
